### ISSUE TITLE
Release new version so old versions no longer break leiningen builds

### ISSUE THREAD

**Issue by flosell** [sroidl/lambda-ui#102]
The last release of LambdaUI still points to an old version of LambdaCD that no longer works with the most recent leiningen version (flosell/lambdacd#171). Because Leiningen tries resolving all dependencies, this breaks builds even when the old LambdaCD version ends up not being used.

#101 already fixed this, it just needs to be released. 

Releated: flosell/lambdacd#173

**Comment by sroidl** [comment]
done, released as 1.0.0
