### ISSUE TITLE
Configurable Navbar

### ISSUE THREAD

**Issue by sroidl** [sroidl/lambda-ui#14]
As as pipeline-user I want to see a navbar on which I can see  useful links (e.g. switch between meta pipeline and release pipeline, external buildtools like gatekeeper, ...). those links should be configurable be the using pipeline.

**Comment by mgeissen** [comment]
suggestion for config state:
config: {
name : "",
baseUrl: "",
urls: { 
1: {url: "https://...", 
      name: "some name for url"},
2: { .....}
}}
