### ISSUE TITLE
Duration on finished builds

### ISSUE THREAD

**Issue by sroidl** [sroidl/lambda-ui#26]
Some finished builds don't seem to have a valid duration. 
This might be due to the polling mechanism currently in place.

The Duration of a build seems to only show the duration of the last build step that ran.
More information is needed. Is this the result of wrong updates from the backend or a bug in the frontend?

**Comment by mgeissen** [comment]
The duration is calculated by the difference between start and end time from summaries in state. This calculation is correct.

Problem: When some Step is ready, the state summary will be updated and the new startTime is the startTime of the current running step. As result, the calculation will use the new startTime of the current running step and the duration time is wrong.

It must be a result of wrong updates from the backend.
