### ISSUE TITLE
Jump to most interesting Step

### ISSUE THREAD

**Issue by rohte** [sroidl/lambda-ui#3]
AS A pipeline user
WHEN a build step failed AND the reason for the failure is substep having failed
I WANT TO see a link to jump to the failed substep automatically.

Usually in the top view of a build, all steps a containers for other steps rather than steps that produce output. Sometimes those container steps contain more containers.
The reason for a failing step then can lie deep within the nested structure of a top level step. 
To see the reason of a failing step quickly I want to be able to jump to the failing step quickly.

**Comment by sroidl** [comment]
updated description
