### ISSUE TITLE
Show last pipeline status in favicon

### ISSUE THREAD

**Issue by hamvocke** [sroidl/lambda-ui#7]
Instead of showing a static lambda favicon in the browser tab it would be awesome to see the status of the last pipeline run in the favicon. This gives users a small indicator providing the latest build status even when they don't have the pipeline tab actively opened in their browser. How cool's that?

Gmail uses this feature to show the unread count in your favicon. Apparently you can [use canvas for that](http://stackoverflow.com/questions/6296574/dynamic-favicon-with-count-like-gmail).

I'd love to see a green lambda icon for a successful pipeline, a red lambda icon for a failed pipeline and a spinning/pulsating/rotating icon for a pipeline that's still in progress. 

Thoughts?

**Comment by sroidl** [comment]
For this we need a nice Icon as well. Maybe ask Tobi about this.
